server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://notification-service:8080
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1

        - id: category-service
          uri: http://category-service:8080
          predicates:
            - Path=/category-service/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: http://product-service:8080
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: cart-service
          uri: http://cart-service:8080
          predicates:
            - Path=/cart-service/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://your-production-frontend.com"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true

eureka:
  client:
    enabled: false
