spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: rajureddy2.konga@gmail.com
    password: kpyx scuk flty lxtc
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 9020

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    hostname: notification-service
