spring:
  data:
    mongodb:
      uri: mongodb://raju:rajureddy98@ac-httvetd-shard-00-00.7s1vkpd.mongodb.net:27017,...
      database: purely_auth_service

server:
  port: 9050

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
